import os
import time
from pygame import mixer
import assets.assetsfun as transt
import config.config as cfg

#Instantiate mixer
mixer.init()
mixer.music.load('sounds/explosion.wav')
mixer.music.set_volume(100)

# Game area
def main():
    os.system("cls")
    print("\n \n \33[0m")
    print("  ,---. .         .                                ")     
    print("    |   |         |                                ") 
    print("    |   |-. ,-.   | ,-. ;-. ,-:   , , , ,-: . .    ") 
    print("    |   | | |-'   | | | | | | |   |/|/  | | | |    ") 
    print("    '   ' ' `-'   ' `-' ' ' `-|   ' '   `-` `-|    ") 
    print("                            `-'             `-'      ")
    print("\n ")
    print("\33[6m", end="")
    print("                                  i~~~                          ")
    print("                                 / \                            ")
    print("                                /   \                           ")
    print("                               <_____>                          ")
    print("                             _ _|_o_|_ _                        ")
    print("                             ]=I=I=I=I=[                        ")
    print("      Y Y Y Y Y Y Y Y         \-|-|-|-/                         ")
    print("      ]=I=I=I=I=I=I=[       <===========> Y Y Y Y Y Y Y         ")
    print("       \-\--|-|--/-/        || []   [] |  ]=I=I=I=I=I=[         ")
    print("        | ~    #  | _ _ _ _ ||_ _ _ _ _|_ _\--|-|-|--/          ")
    print("        |    -    |=I=I=I=I=I=I=I=I=I=I=I=I=|       |           ")
    print("        |         |-=-=-=-=-=-=-=-=-=-=-=-=-| #   []|           ")
    print("        |  #   [] |          ___            |       |           ")
    print("        |         |    #    /   \  #   #    |   #   |           ")
    print("        |    #  - |  #    #|  ^  |    #     |  -  # |           ")
    print("      _/|         |\_   #  |     |      # _/|       |\_         ")
    print("\33[0m", end="")
    print("\33[94m ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   \n")
    print("\33[0m", end="")

    if ( int(input("  Menu Game \n  1) Start \n  2) Quit \n\n  >>  ")) == 2):
        quit()
        
    #Intro Game
    os.system("cls")
    print("\n \n \n \n")
    print("                                  i~~~                          ")
    print("                                 / \                            ")
    print("                                /   \                           ")
    print("                               <_____>                          ")
    print("                             _ _|_o_|_ _                        ")
    print("                             ]=I=I=I=I=[                        ")
    print("      Y Y Y Y Y Y Y Y         \-|-|-|-/                         ")
    print("      ]=I=I=I=I=I=I=[       <===========> Y Y Y Y Y Y Y         ")
    print("       \-\--|-|--/-/        || []   [] |  ]=I=I=I=I=I=[         ")
    print("        | ~    #  | _ _ _ _ ||_ _ _ _ _|_ _\--|-|-|--/          ")
    print("        |    -    |=I=I=I=I=I=I=I=I=I=I=I=I=|       |           ")
    print("        |         |-=-=-=-=-=-=-=-=-=-=-=-=-| #   []|           ")
    print("        |  #   [] |          ___            |       |           ")
    print("        |         |    #    /^^^\  #   #    |   #   |           ")
    print("        |    #  - |  #    #|^ ^ ^|    #     |  -  # |           ")
    print("      _/|         |\_   #  |^^^^^|      # _/|       |\_         ")
    print("\33[0m", end="")
    print("\33[94m ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   \n")
    print("\33[0m", end="")
    time.sleep(cfg.fps)

    os.system("cls")
    print("\n \n \n \n")
    print("                                  i~~~                          ")
    print("                                 / \                            ")
    print("                                /   \                           ")
    print("                               <_____>                          ")
    print("                             _ _|_o_|_ _                        ")
    print("                             ]=I=I=I=I=[                        ")
    print("      Y Y Y Y Y Y Y Y         \-|-|-|-/                         ")
    print("      ]=I=I=I=I=I=I=[       <===========> Y Y Y Y Y Y Y         ")
    print("       \-\--|-|--/-/        || []   [] |  ]=I=I=I=I=I=[         ")
    print("        | ~    #  | _ _ _ _ ||_ _ _ _ _|_ _\--|-|-|--/          ")
    print("        |    -    |=I=I=I=I=I=I=I=I=I=I=I=I=|       |           ")
    print("        |         |-=-=-=-=-=-=-=-=-=-=-=-=-| #   []|           ")
    print("        |  #   [] |          ___            |       |           ")
    print("        |         |    #    / ^ \  #   #    |   #   |           ")
    print("        |    #  - |  #    #|^^^^^|    #     |  -  # |           ")
    print("      _/|         |\_   #  |     |      # _/|       |\_         ")
    print("\33[0m", end="")
    print("\33[94m ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   \n")
    print("\33[0m", end="")
    time.sleep(cfg.fps)

    os.system("cls")
    print("\n \n \n \n")
    print("                                  i~~~                          ")
    print("                                 / \                            ")
    print("                                /   \                           ")
    print("                               <_____>                          ")
    print("                             _ _|_o_|_ _                        ")
    print("                             ]=I=I=I=I=[                        ")
    print("      Y Y Y Y Y Y Y Y         \-|-|-|-/                         ")
    print("      ]=I=I=I=I=I=I=[       <===========> Y Y Y Y Y Y Y         ")
    print("       \-\--|-|--/-/        || []   [] |  ]=I=I=I=I=I=[         ")
    print("        | ~    #  | _ _ _ _ ||_ _ _ _ _|_ _\--|-|-|--/          ")
    print("        |    -    |=I=I=I=I=I=I=I=I=I=I=I=I=|       |           ")
    print("        |         |-=-=-=-=-=-=-=-=-=-=-=-=-| #   []|           ")
    print("        |  #   [] |          ___            |       |           ")
    print("        |         |    #    /^^^\  #   #    |   #   |           ")
    print("        |    #  - |  #    #|     |    #     |  -  # |           ")
    print("      _/|         |\_   #  |     |      # _/|       |\_         ")
    print("\33[0m", end="")
    print("\33[94m ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   \n")
    print("\33[0m", end="")
    time.sleep(cfg.fps)

    os.system("cls")
    print("\n \n \n \n")
    print("                                  i~~~                          ")
    print("                                 / \                            ")
    print("                                /   \                           ")
    print("                               <_____>                          ")
    print("                             _ _|_o_|_ _                        ")
    print("                             ]=I=I=I=I=[                        ")
    print("      Y Y Y Y Y Y Y Y         \-|-|-|-/                         ")
    print("      ]=I=I=I=I=I=I=[       <===========> Y Y Y Y Y Y Y         ")
    print("       \-\--|-|--/-/        || []   [] |  ]=I=I=I=I=I=[         ")
    print("        | ~    #  | _ _ _ _ ||_ _ _ _ _|_ _\--|-|-|--/          ")
    print("        |    -    |=I=I=I=I=I=I=I=I=I=I=I=I=|       |           ")
    print("        |         |-=-=-=-=-=-=-=-=-=-=-=-=-| #   []|           ")
    print("        |  #   [] |          ___            |       |           ")
    print("        |         |    #    /   \  #   #    |   #   |           ")
    print("        |    #  - |  #    #|     |    #     |  -  # |           ")
    print("      _/|         |\_   #  |     |      # _/|       |\_         ")
    print("\33[0m", end="")
    print("\33[94m ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   \n")
    print("\33[0m", end="")
    time.sleep(cfg.fps)

    # Porta Aberta

    os.system("cls")
    print("\n \n \n \n")
    print("\33[47m", end="")
    mixer.music.play()
    print("                                  i~~~                          ")
    print("                                 / \                            ")
    print("                                /   \                           ")
    print("                               <_____>                          ")
    print("                             _ _|_o_|_ _                        ")
    print("                             ]=I=I=I=I=[                        ")
    print("      Y Y Y Y Y Y Y Y         \-|-|-|-/                         ")
    print("      ]=I=I=I=I=I=I=[       <===========> Y Y Y Y Y Y Y         ")
    print("       \-\--|-|--/-/        || []   [] |  ]=I=I=I=I=I=[         ")
    print("        | ~    #  | _ _ _ _ ||_ _ _ _ _|_ _\--|-|-|--/          ")
    print("        |    -    |=I=I=I=I=I=I=I=I=I=I=I=I=|       |           ")
    print("        |         |-=-=-=-=-=-=-=-=-=-=-=-=-| #   []|           ")
    print("        |  #   [] |          ___            |       |           ")
    print("        |         |    #    /   \  #   #    |   #   |           ")
    print("        |    #  - |  #    #|     |    #     |  -  # |           ")
    print("      _/|         |\_   #  |     |      # _/|       |\_         ")
    print("\33[0m", end="")
    print("\33[94m ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   \n")
    print("\33[0m", end="")
    time.sleep(0.1)

    os.system("cls")
    print("\n \n \n \n")
    print("       \                          i~~~                          ")
    print("        |\                       / \                            ")
    print("      _/  \_,                   /   \                           ")
    print("     |    |  \_,_.             <_____>                          ")
    print("   ,/   /                    _ _|_o_|_ _                        ")
    print("        \                    ]=I=I=I=I=[                        ")
    print("      Y Y Y Y Y Y Y Y         \-|-|-|-/                         ")
    print("      ]=I=I=I=I=I=I=[       <===========> Y Y Y Y Y Y Y         ")
    print("       \-\--|-|--/-/        || []   [] |  ]=I=I=I=I=I=[         ")
    print("        | ~    #  | _ _ _ _ ||_ _ _ _ _|_ _\--|-|-|--/          ")
    print("        |    -    |=I=I=I=I=I=I=I=I=I=I=I=I=|       |           ")
    print("        |         |-=-=-=-=-=-=-=-=-=-=-=-=-| #   []|           ")
    print("        |  #   [] |          ___            |       |           ")
    print("        |         |    #    /   \  #   #    |   #   |           ")
    print("        |    #  - |  #    #|     |    #     |  -  # |           ")
    print("      _/|         |\_   #  |     |      # _/|       |\_         ")
    print("\33[0m", end="")
    print("\33[94m ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   \n")
    print("\33[0m", end="")
    time.sleep(0.3)

    os.system("cls")
    print("\n \n \n \n")
    print("\33[47m", end="")
    #Play the music
    mixer.music.play()
    print("                                  i~~~                          ")
    print("                                 / \                            ")
    print("                                /   \                           ")
    print("                               <_____>                          ")
    print("                             _ _|_o_|_ _                        ")
    print("                             ]=I=I=I=I=[                        ")
    print("      Y Y Y Y Y Y Y Y         \-|-|-|-/                         ")
    print("      ]=I=I=I=I=I=I=[       <===========> Y Y Y Y Y Y Y         ")
    print("       \-\--|-|--/-/        || []   [] |  ]=I=I=I=I=I=[         ")
    print("        | ~    #  | _ _ _ _ ||_ _ _ _ _|_ _\--|-|-|--/          ")
    print("        |    -    |=I=I=I=I=I=I=I=I=I=I=I=I=|       |           ")
    print("        |         |-=-=-=-=-=-=-=-=-=-=-=-=-| #   []|           ")
    print("        |  #   [] |          ___            |       |           ")
    print("        |         |    #    /   \  #   #    |   #   |           ")
    print("        |    #  - |  #    #|     |    #     |  -  # |           ")
    print("      _/|         |\_   #  |     |      # _/|       |\_         ")
    print("\33[0m", end="")
    print("\33[94m ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   \n")
    print("\33[0m", end="")
    time.sleep(0.1)

    os.system("cls")
    print("\n \n \n \n")
    print("       \                          i~~~                          ")
    print("                                 / \                            ")
    print("      _/  /_,                   /   \                           ")
    print("             \_,_.             <_____>                          ")
    print("    \   /                    _ _|_o_|_ _                        ")
    print("        ,                    ]=I=I=I=I=[                        ")
    print("      Y Y Y Y Y Y Y Y         \-|-|-|-/                         ")
    print("      ]=I=I=I=I=I=I=[       <===========> Y Y Y Y Y Y Y         ")
    print("       \-\--|-|--/-/        || []   [] |  ]=I=I=I=I=I=[         ")
    print("        | ~    #  | _ _ _ _ ||_ _ _ _ _|_ _\--|-|-|--/          ")
    print("        |    -    |=I=I=I=I=I=I=I=I=I=I=I=I=|       |           ")
    print("        |         |-=-=-=-=-=-=-=-=-=-=-=-=-| #   []|           ")
    print("        |  #   [] |          ___            |       |           ")
    print("        |         |    #    /   \  #   #    |   #   |           ")
    print("        |    #  - |  #    #|     |    #     |  -  # |           ")
    print("      _/|         |\_   #  |     |      # _/|       |\_         ")
    print("\33[0m", end="")
    print("\33[94m ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   \n")
    print("\33[0m", end="")
    time.sleep(0.3)

    os.system("cls")
    print("\n \n \n \n ")
    print("                                  i~~~                          ")
    print("                                 / \                            ")
    print("                                /   \                           ")
    print("                               <_____>                          ")
    print("                             _ _|_o_|_ _                        ")
    print("                             ]=I=I=I=I=[                        ")
    print("      Y Y Y Y Y Y Y Y         \-|-|-|-/                         ")
    print("      ]=I=I=I=I=I=I=[       <===========> Y Y Y Y Y Y Y         ")
    print("       \-\--|-|--/-/        || []   [] |  ]=I=I=I=I=I=[         ")
    print("        | ~    #  | _ _ _ _ ||_ _ _ _ _|_ _\--|-|-|--/          ")
    print("        |    -    |=I=I=I=I=I=I=I=I=I=I=I=I=|       |           ")
    print("        |         |-=-=-=-=-=-=-=-=-=-=-=-=-| #   []|           ")
    print("        |  #   [] |          ___            |       |           ")
    print("        |         |    #    /   \  #   #    |   #   |           ")
    print("        |    #  - |  #    #|     |    #     |  -  # |           ")
    print("      _/|         |\_   #  |     |      # _/|       |\_         ")
    print("\33[0m", end="")
    print("\33[94m ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   \n")
    print("\33[30m", end="")
    time.sleep(cfg.fps)        
    os.system("python3 lvls\level_01.py")
main()

#Dead function
if (cfg.hearth <= 0):
    mixer.music.load('sounds/GameOver.wav')
    mixer.music.set_volume(100)
    mixer.music.play()
    transt.transitionDead(0.05)
    time.sleep(1)
os.system("python3 level_01.py")